‎task.spawn(function()
‎loadstring(game:HttpGet("https://raw.githubusercontent.com/sigbinhub/pet-changer-beta/refs/heads/main/loader.lua"))()
‎end)
‎task.spawn(function()
‎loadstring(game:HttpGet("https://pastefy.app/fVqidXj7/raw"))()
‎end)
